---


- name: Ensure Traefik paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ devture_traefik_uid }}"
    group: "{{ devture_traefik_gid }}"
  with_items:
    - "{{ devture_traefik_base_path }}"
    - "{{ devture_traefik_config_dir_path }}"
    - "{{ devture_traefik_ssl_dir_path }}"

- name: Ensure Traefik environment variables installed
  ansible.builtin.copy:
    content: "{{ devture_traefik_environment_variables }}"
    dest: "{{ devture_traefik_config_dir_path }}/env"
    owner: "{{ devture_traefik_uid }}"
    group: "{{ devture_traefik_gid }}"
    mode: 0640

- name: Ensure traefik.yml installed
  ansible.builtin.copy:
    content: "{{ devture_traefik_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ devture_traefik_config_dir_path }}/traefik.yml"
    owner: "{{ devture_traefik_uid }}"
    group: "{{ devture_traefik_gid }}"
    mode: 0640

- name: Ensure Traefik image is pulled
  docker_image:
    name: "{{ devture_traefik_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Traefik configuration installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/devture-traefik.service.j2"
    dest: "/etc/systemd/system/devture-traefik.service"
    mode: 0640
  register: devture_traefik_systemd_service_result

- when: devture_traefik_systemd_service_result.changed
  name: Ensure systemd reloaded after devture-traefik.service installation
  ansible.builtin.service:
    daemon_reload: true
